import {
    FaReact,
    FaNodeJs,
    FaLaravel,
    FaPhp,
    FaGitAlt,
    FaGithub,
    FaFigma,
    FaBootstrap,
    FaVuejs,
    FaAngular,
    FaPython,
    FaJava,
    FaHtml5,
    FaCss3Alt,
    FaDocker,
    FaAws,
    FaSass,
    FaLinux,
    FaNpm,
} from "react-icons/fa";

import {
    SiNextdotjs,
    SiJavascript,
    SiTypescript,
    SiTailwindcss,
    SiPostgresql,
    SiMysql,
    SiMongodb,
    SiExpress,
    SiRedux,
    SiGraphql,
    SiFirebase,
    SiVite,
    SiJest,
    SiWebpack,
    SiPostman,
    SiFlutter,
    SiKotlin,
    SiSwift,
    SiDjango,
    SiSpring,
} from "react-icons/si";

import { VscCode } from "react-icons/vsc";

export const SKILL_ICONS = [
    { key: "FaReact", label: "React", icon: FaReact },
    { key: "SiNextdotjs", label: "Next.js", icon: SiNextdotjs },
    { key: "FaVuejs", label: "Vue.js", icon: FaVuejs },
    { key: "FaAngular", label: "Angular", icon: FaAngular },
    { key: "SiJavascript", label: "JavaScript", icon: SiJavascript },
    { key: "SiTypescript", label: "TypeScript", icon: SiTypescript },
    { key: "SiTailwindcss", label: "Tailwind CSS", icon: SiTailwindcss },
    { key: "FaBootstrap", label: "Bootstrap", icon: FaBootstrap },
    { key: "FaSass", label: "Sass", icon: FaSass },
    { key: "FaHtml5", label: "HTML5", icon: FaHtml5 },
    { key: "FaCss3Alt", label: "CSS3", icon: FaCss3Alt },
    { key: "SiRedux", label: "Redux", icon: SiRedux },
    { key: "SiVite", label: "Vite", icon: SiVite },
    { key: "FaNodeJs", label: "Node.js", icon: FaNodeJs },
    { key: "SiExpress", label: "Express.js", icon: SiExpress },
    { key: "FaLaravel", label: "Laravel", icon: FaLaravel },
    { key: "FaPhp", label: "PHP", icon: FaPhp },
    { key: "SiDjango", label: "Django", icon: SiDjango },
    { key: "SiSpring", label: "Spring", icon: SiSpring },
    { key: "FaPython", label: "Python", icon: FaPython },
    { key: "FaJava", label: "Java", icon: FaJava },
    { key: "SiGraphql", label: "GraphQL", icon: SiGraphql },
    { key: "SiPostgresql", label: "PostgreSQL", icon: SiPostgresql },
    { key: "SiMysql", label: "MySQL", icon: SiMysql },
    { key: "SiMongodb", label: "MongoDB", icon: SiMongodb },
    { key: "SiFirebase", label: "Firebase", icon: SiFirebase },
    { key: "FaAws", label: "AWS", icon: FaAws },
    { key: "FaDocker", label: "Docker", icon: FaDocker },
    { key: "FaLinux", label: "Linux", icon: FaLinux },
    { key: "FaGitAlt", label: "Git", icon: FaGitAlt },
    { key: "FaGithub", label: "GitHub", icon: FaGithub },
    { key: "SiPostman", label: "Postman", icon: SiPostman },
    { key: "SiJest", label: "Jest", icon: SiJest },
    { key: "SiWebpack", label: "Webpack", icon: SiWebpack },
    { key: "FaNpm", label: "npm", icon: FaNpm },
    { key: "FaFigma", label: "Figma", icon: FaFigma },
    { key: "VscCode", label: "VS Code", icon: VscCode },
    { key: "SiFlutter", label: "Flutter", icon: SiFlutter },
    { key: "SiKotlin", label: "Kotlin", icon: SiKotlin },
    { key: "SiSwift", label: "Swift", icon: SiSwift },
];

export function getSkillIcon(key) {
    return SKILL_ICONS.find((item) => item.key === key)?.icon || null;
}
